type SET_CURRENT_EXPANDED_COLLECTIONS = {
  type: "SET_CURRENT_EXPANDED_COLLECTIONS";
  payload: string[];
};

type SET_SELECTED_COLLECTION = {
  type: "SET_SELECTED_COLLECTION";
  payload: string;
};

export type Effect = SET_CURRENT_EXPANDED_COLLECTIONS | SET_SELECTED_COLLECTION;
